# Generated by Django 4.0.5 on 2023-04-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_remove_companymanager_is_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="director",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director_company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
