# Generated by Django 4.0.5 on 2023-05-08 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymanager',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymanager',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
