version: "3.9"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./job_finder/.env
    ports:
      - "5432:5432"
  backend:
    build: job_finder
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./job_finder:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - job_finder/.env
    depends_on:
      - db
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
  celery:
    build: ./job_finder
    command: celery -A job_finder worker -B
    volumes:
      - ./job_finder:/app/backend
    depends_on:
      - rabbitmq
      - backend
volumes:
  postgres_data:
