# Generated by Django 4.0.5 on 2023-04-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_companymanager_is_general"),
        ("vacancies", "0002_alter_vacancy_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="companies.companymanager",
            ),
        ),
    ]
