# Generated by Django 4.0.5 on 2023-05-08 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='City'),
            preserve_default=False,
        ),
    ]
