# Generated by Django 4.0.5 on 2023-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_options_alter_vacancy_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience_option',
            field=models.CharField(choices=[('0', '0 лет'), ('1-3', '1-3 года'), ('3-5', '3-5 лет'), ('5+', '5+ лет')], default='0', max_length=4, verbose_name='Years of experience'),
        ),
    ]
