# Generated by Django 4.0.5 on 2023-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0002_vacancyresponse_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
