# Generated by Django 4.0.5 on 2023-02-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0003_delete_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancyresponse",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "VacancyResponses",
            },
        ),
    ]
