# Generated by Django 4.0.5 on 2023-01-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Phone number"
            ),
        ),
    ]
