# Generated by Django 4.0.5 on 2023-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_manager'),
        ('users', '0004_remove_companymanager_user_ptr_companymanager_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyManager',
        ),
    ]
