# Generated by Django 4.0.5 on 2023-04-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0004_alter_resume_languages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancies", "0003_alter_vacancy_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="vacancyview",
            constraint=models.UniqueConstraint(
                fields=("user", "vacancy"), name="uq_user_vacancy"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeview",
            constraint=models.UniqueConstraint(
                fields=("user", "resume"), name="uq_user_resume"
            ),
        ),
    ]
