# Generated by Django 4.0.5 on 2023-04-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("views", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumeview",
            options={"verbose_name_plural": "Views"},
        ),
        migrations.AlterModelOptions(
            name="vacancyview",
            options={"verbose_name_plural": "Views"},
        ),
        migrations.RemoveConstraint(
            model_name="resumeview",
            name="uq_user_resume",
        ),
        migrations.RemoveConstraint(
            model_name="vacancyview",
            name="uq_user_vacancy",
        ),
    ]
