# Generated by Django 4.0.5 on 2023-04-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_companymanager_is_general"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("views", "0002_alter_resumeview_options_alter_vacancyview_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumeview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vacancyview",
            options={},
        ),
        migrations.RemoveField(
            model_name="resumeview",
            name="user",
        ),
        migrations.AddField(
            model_name="resumeview",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="companies.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vacancyview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
