# Generated by Django 4.0.5 on 2023-04-19 20:33

from django.db import migrations, models
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_alter_resume_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=resumes.models.cv_generate_upload_path,
                verbose_name="CV",
            ),
        ),
    ]
