# Generated by Django 4.0.5 on 2023-04-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0006_alter_resume_languages_alter_resume_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
