# Generated by Django 4.0.5 on 2023-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0007_alter_resume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Experience",
            ),
        ),
    ]
