# Generated by Django 4.0.5 on 2023-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0008_alter_resume_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                verbose_name="Experience years",
            ),
        ),
    ]
