# Generated by Django 4.0.5 on 2023-05-02 20:48

from django.db import migrations, models
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resumes.models.avatar_generate_upload_path, verbose_name='Avatar'),
        ),
    ]
