# Generated by Django 4.0.5 on 2023-05-21 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
