# Generated by Django 4.0.5 on 2023-06-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_resume_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'Resumes'},
        ),
    ]
