# Generated by Django 4.0.5 on 2023-05-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_messages', '0002_message_is_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created'], 'verbose_name_plural': 'Messages'},
        ),
    ]
